version: "3.9"

services:
  db:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_USER_USERNAME: "${MONGO_USER_USERNAME}"
      MONGO_USER_PASSWORD: "${MONGO_USER_PASSWORD}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - ./backend/db/data:/data/db
      - ./backend/db/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - backend

  api:
    build:
      context: ./backend
    container_name: api
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - 8004:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge
